### PR TITLE
New api

### PR DESCRIPTION
**Pull request by kgelinas**
Not tested but should work

### CODE REVIEW

**Comment by eiabea** [comment]
Thank you for the PR, i quickly looked into the changes and i do not think that they are going to work out of the box.
Could you please test them out?

**Comment by kgelinas** [comment]
Tried to build it last two hours.
I'm no develloper so i'll let you handle your app...

**Comment by eiabea** [comment]
Okay, but the basic idea is to have an additional price ticker source from blockchain.info?

**Comment by kgelinas** [comment]
Sorry this was a poor try at adding blockchain as a price source last year.
I will resync the repo and only add the /btc/ to the api of slushpool that
is now required

**Pull request closed without merging**
